services:
  typescript:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - type: bind
        source: ../rust-pentagram/workspace
        target: /workspace/rust
      - type: bind
        source: ../typescript-pentagram-rotate
        target: /workspace/typescript
    user: utakata
    tty: true